/// Describes a single column in a table.
///
/// Generated by `#[derive(DocxRow)]` from field annotations.
/// Analogous to `ExcelColumn` in `easyexcel-rust`.
#[derive(Debug, Clone)]
pub struct TableColumn {
    /// Column header text (displayed in the table header row).
    pub name: String,
    /// Rust field name (used for reverse lookup).
    pub field_name: String,
    /// Zero-based column index in the table.
    pub index: usize,
    /// Order for column sorting (lower = leftmost).
    pub order: u32,
    /// Preferred column width as a fraction of page width (0.0–1.0),
    /// or `None` for auto-width.
    pub width: Option<f64>,
    /// Date/time format pattern (e.g. `"%Y-%m-%d"`), if applicable.
    pub format: Option<String>,
    /// Whether the field should be ignored during read/write.
    pub ignored: bool,
}

impl TableColumn {
    /// Creates a new column descriptor.
    #[must_use]
    pub fn new(name: impl Into<String>, field_name: impl Into<String>, index: usize) -> Self {
        Self {
            name: name.into(),
            field_name: field_name.into(),
            index,
            order: index as u32,
            width: None,
            format: None,
            ignored: false,
        }
    }

    /// Sets the display name.
    #[must_use]
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.name = name.into();
        self
    }

    /// Sets the column order.
    #[must_use]
    pub fn order(mut self, order: u32) -> Self {
        self.order = order;
        self
    }

    /// Sets the column width as a fraction (0.0–1.0).
    #[must_use]
    pub fn width(mut self, width: f64) -> Self {
        self.width = Some(width);
        self
    }

    /// Sets the format pattern for date/datetime columns.
    #[must_use]
    pub fn format(mut self, format: impl Into<String>) -> Self {
        self.format = Some(format.into());
        self
    }

    /// Marks this column as ignored during read/write.
    #[must_use]
    pub fn ignore(mut self) -> Self {
        self.ignored = true;
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn column_new() {
        let c = TableColumn::new("Name", "name", 0);
        assert_eq!(c.name, "Name");
        assert_eq!(c.field_name, "name");
        assert_eq!(c.index, 0);
        assert_eq!(c.order, 0);
        assert!(c.width.is_none());
        assert!(c.format.is_none());
        assert!(!c.ignored);
    }

    #[test]
    fn column_builder_chain() {
        let c = TableColumn::new("Age", "age", 1)
            .name("User Age")
            .order(5)
            .width(0.3)
            .format("%Y-%m-%d")
            .ignore();
        assert_eq!(c.name, "User Age");
        assert_eq!(c.order, 5);
        assert_eq!(c.width, Some(0.3));
        assert_eq!(c.format.as_deref(), Some("%Y-%m-%d"));
        assert!(c.ignored);
    }
}
