[package]
name = "easydoc-reader"
description = "DOCX/DOC document reader for easydoc-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
easydoc-core = { path = "../easydoc-core", version = "0.1.0-alpha.2" }
office_oxide.workspace = true
quick-xml.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
proptest.workspace = true
easydoc-writer = { path = "../easydoc-writer", version = "0.1.0-alpha.2" }

[lints]
workspace = true
