[package]
name = "easydoc-docx"
description = "DOCX renderer for easydoc-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
docx-rs.workspace = true
easydoc-core.workspace = true

[dev-dependencies]
zip.workspace = true

[lints]
workspace = true
